In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,7,8]])

In [3]:
myarr[0,2]

np.int64(7)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.size

4

In [6]:
objectarr = np.array({34, 64, 64})

In [7]:
objectarr

array({64, 34}, dtype=object)

In [8]:
rnge = np.arange(15) # gives a numpy array of range 15

In [9]:
rnge

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
lspace = np.linspace(1, 5, 12) # give an array of 12 elements in between 1 and 5 which are linearly space
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [11]:
emp = np.empty((4,6)) # give an array of 4,6 of random elements
emp

array([[ 5.17041877e-310,  0.00000000e+000,  1.79240057e-313,
         7.07721246e-308,  1.33360311e+241,  4.64165359e-310],
       [ 1.93676345e-282,  2.02534551e-312,  7.76342176e-307,
         1.33360292e+241,  3.50129306e-311,  4.31912682e-239],
       [ 3.06528923e-313,  1.68400738e-019,  1.10811151e-302,
         1.28272988e-312,  1.45859717e-303,  6.30418685e-246],
       [-9.60207907e+303,  3.71791919e-294,  3.39598095e+130,
         1.69822916e-072,  2.67923915e-101,  8.93713865e-317]])

In [12]:
emp_like = np.empty_like(lspace) # give a array to it , it gives a dulpicate for that
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [13]:
arr = np.arange(99)
arr



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [14]:
arr.reshape(3, 33) # reshape 3X1 array and 3 * 33 = 99
# keep in mind arr does not change




array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [15]:
# To change arr 

arr = arr.reshape(3, 33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [16]:
arr = arr.ravel() # to make it back into shape
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [17]:
arr.shape

(99,)

In [18]:
x = [[1,2,3], [4,5,6], [7,8,9]]
ar = np.array(x)

ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
ar.sum(axis = 0)


array([12, 15, 18])

In [20]:
ar.sum(axis = 1)

array([ 6, 15, 24])

In [21]:
ar.T # transpose the array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
for item in ar.flat: # it gives a iterator
    print(item)

1
2
3
4
5
6
7
8
9


In [23]:
ar.ndim # gives number of dimension

2

In [24]:
ar.size # we running it as attributes

9

In [25]:
ar.nbytes # tell us how many bytes array is consuming

72

In [27]:
one = np.array([1, 3, 7, 994, 6])
one.argmax() # tell us at which index we have our max element  # we running as method 

np.int64(3)

In [28]:
one.argmin() # tell us at which index we have our min element

np.int64(0)

In [29]:
one.argsort() # give order of index in which we get a sorted array

array([0, 1, 4, 2, 3])

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
ar.argmax() # it arrange it in one row then count the index

np.int64(8)

In [33]:
ar.argmax(axis = 0) # give max element of each column

array([2, 2, 2])

In [35]:
ar2 = ar.T
ar2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [36]:
ar + ar2 # cannot do same in list

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [37]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [38]:
np.sqrt(ar2)

array([[1.        , 2.        , 2.64575131],
       [1.41421356, 2.23606798, 2.82842712],
       [1.73205081, 2.44948974, 3.        ]])

In [39]:
ar.sum()

np.int64(45)

In [40]:
ar.max()

np.int64(9)

In [42]:
np.where(ar>5) # (1,2) (2,0) ...

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))